In [1]:
import numpy as np

In [3]:
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [5]:
data = np.random.randn(7, 4)
data

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625],
       [ 0.07688918, -1.32467422, -0.23178167, -0.02319271],
       [ 0.632871  , -0.6483917 ,  0.92984244, -2.85619274],
       [-0.00908062,  0.20208639, -0.01026422,  1.02360458],
       [ 0.52287401, -0.75676249,  2.00997238, -0.2449475 ],
       [-1.29562986,  0.32078675,  1.10612366,  0.3697646 ]])

In [6]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [7]:
data[names == 'Hasan']

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [-0.00908062,  0.20208639, -0.01026422,  1.02360458]])

In [9]:
data[names == 'Elyor']

array([[ 0.632871  , -0.6483917 ,  0.92984244, -2.85619274],
       [-1.29562986,  0.32078675,  1.10612366,  0.3697646 ]])

In [10]:
data[names == 'Husan']

array([[ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625]])

In [11]:
data[names != 'Elyor'] # != -teng bo`lmasa

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625],
       [ 0.07688918, -1.32467422, -0.23178167, -0.02319271],
       [-0.00908062,  0.20208639, -0.01026422,  1.02360458],
       [ 0.52287401, -0.75676249,  2.00997238, -0.2449475 ]])

In [12]:
data[~(names == 'Elyor')] # ~ teng bo`lmasa

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625],
       [ 0.07688918, -1.32467422, -0.23178167, -0.02319271],
       [-0.00908062,  0.20208639, -0.01026422,  1.02360458],
       [ 0.52287401, -0.75676249,  2.00997238, -0.2449475 ]])

In [13]:
egzaklar = (names == 'Hasan') | (names == 'Husan')  # | (or) yoki
egzaklar

array([ True,  True, False, False,  True, False, False])

In [14]:
data[egzaklar]

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625],
       [-0.00908062,  0.20208639, -0.01026422,  1.02360458]])

In [15]:
data[data<0]

array([-0.36782417, -0.13408739, -0.0048783 , -1.32467422, -0.23178167,
       -0.02319271, -0.6483917 , -2.85619274, -0.00908062, -0.01026422,
       -0.75676249, -0.2449475 , -1.29562986])

In [21]:
data[:3]

array([[ 0.15681838, -0.36782417,  0.09474427, -0.13408739],
       [ 0.62756211, -0.0048783 ,  1.65985513,  0.08731625],
       [ 0.07688918, -1.32467422, -0.23178167, -0.02319271]])