In [1]:
import numpy as np


In [4]:
arr = np.arange(6).reshape(3, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
arr.T # Trasnpose bu massiv(array) o`qlarini almashtiradi

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
arr.swapaxes(1, 0) #Trasnposeni amalga oshirishning boshqacha usuli swaping axes

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
arr.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [13]:
np.dot(arr, arr.T)  # AA^T arr massivini A^T trasnpose bilan bo`paytirish

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])