In [1]:
import numpy as np

In [8]:
arr1 = np.arange(10, 100, 10)
arr1[-5]

50

In [9]:
arr1[3:6]

array([40, 50, 60])

In [13]:
arr2 = arr1[3:6]  
arr1

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [14]:
arr2[:] = 0   #arr1 dan olgan elementlarga 0 qiymatga o`zgartiramiz
arr2

array([0, 0, 0])

In [12]:
arr1    #yuqoridagi arr2 ga kiritilgan o`zgarishlar arr1 ham tasir qiladi

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [16]:
arr3 = np.arange(2, 20, 2)
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr4 = arr3[3:6].copy() #copy funksiyasidan foydalanib arr3 dan elementlarni olamiz
arr4


array([ 8, 10, 12])

In [19]:
arr4[:] = 0
arr4

array([0, 0, 0])

In [20]:
arr3  #arr4 ga kiritilgan o`zgartirishlar arr3 ga tasir qilmadi

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])