In [1]:
import numpy as np

**N o`lchovli massivlar(arraylar)ga ishlov berish**

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2 o`lchovli massiv
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr_2d[1, 1]

5

In [6]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [8]:
arr_2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [14]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
arr_3d


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [16]:
arr_3d.shape

(3, 3, 3)

In [17]:
arr_3d[0][1, 1]


5

In [18]:
arr_3d[1][1, 1]

14

In [19]:
arr_3d[2][1, 1]

23

In [20]:
arr_3d[1][1:, :]

array([[13, 14, 15],
       [16, 17, 18]])