In [2]:
import numpy as np

In [11]:
list1 = [1, 3, 55, 6, 7, 2, 5]
arr1 = np.array(list1)  #listni arrayga o`tkazyapmiz

In [12]:
tuple1 = (3, 6, 1, 32, 65, 86, 86)
arr2 = np.array(tuple1) #tupleni arrayga o`tkazyapmiz

In [14]:
#arraylarning o`lchamlarini tekshirib ko`ramiz
#o`lchamini .ndim funksiyasi orqali tekshiramiz
print(arr1.ndim)
print(arr2.ndim)

1
1


In [18]:
two_list = ([3, 5, 2, 8, 1], [9, 34, 2, 1, 6])
arr3 = np.array(two_list)
print(arr3.ndim)

2


In [19]:
arr3.shape # qatorlar va ustunlar soni(q, u)

(2, 5)

In [21]:
arr3.size # arraydagi elementlar soni

10

In [23]:
arr4 = np.zeros((3, 4)) # faqat 0 dan iborat array yaratish
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
arr5 = np.ones((3, 4)) # faqar 1 dan iborat array yaratish
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
arr6 = np.arange(1, 15, 2) # arange funksiyasi 1, dan 15 oraligidagi sonlarni 2 qadam bilan array yaratish
print(arr6)

[ 1  3  5  7  9 11 13]
