In [1]:
import numpy as np

numbers = np.arange(10, 100, 5)


In [2]:
numbers = np.arange(1, 10)
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.sqrt(numbers)    # massiv elementlarining ildizini aniqlaydi

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.square(numbers)   # massiv elementlarining kvadratini aniqlaydi

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
np.square(numbers.reshape(3,3))

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
np.exp(numbers)   #massiv elementlarini exponentini aniqlaydi

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [17]:
np.log(numbers[1:])   # massiv elementlarining (0 dan tashqari) logarifmini qaytaradi

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458])

In [20]:
arr = np.random.randn(6)


In [24]:
qoldiq, butun = np.modf(arr)    #massiv elementlari butun va qoldiq qismga ajratadi


In [25]:
qoldiq

array([-0.58984656, -0.87952616,  0.01512461, -0.17363651, -0.75935976,
        0.69884473])

In [26]:
butun

array([-0., -0.,  1., -0., -0.,  0.])