In [1]:
import numpy as np

In [2]:
number = np.random.randn(4, 4)

Mantiqiy shart operatori

In [3]:
#where
cond = np.where(number<0, 10, 30)
cond


array([[10, 30, 30, 10],
       [30, 30, 10, 10],
       [30, 30, 10, 10],
       [30, 10, 10, 10]])

In [4]:
number

array([[-0.31653532,  0.82618064,  2.13783883, -0.45612969],
       [ 0.32377004,  0.45668323, -0.11089685, -0.3792    ],
       [ 0.31130048,  1.02887065, -1.84070781, -1.04391198],
       [ 1.87271977, -0.27590879, -0.43765623, -0.72042197]])

In [5]:
booleans = [True, False, True, False]
np.where(booleans, number, 0)

array([[-0.31653532,  0.        ,  2.13783883,  0.        ],
       [ 0.32377004,  0.        , -0.11089685,  0.        ],
       [ 0.31130048,  0.        , -1.84070781,  0.        ],
       [ 1.87271977,  0.        , -0.43765623,  0.        ]])